{% set name = "mdtraj" %}
{% set version = "1.10.3" %}

package:
  name: mdtraj
  version: {{ version }}

source:
  git_url: https://github.com/mdtraj/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython =3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - versioneer
  host:
    - python
    - pip
    - setuptools
    - versioneer
    - cython =3
    - numpy
    - zlib
  run:
    - python
    - setuptools
    - packaging
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas
    - pyparsing
    - pytables
    - snappy
    - zlib
  run_constrained:
    # https://github.com/MDAnalysis/mdanalysis/issues/4172; 2.x and 3.0.1 seem fine
    - gsd !=3.0.0

test:
  imports:
    - mdtraj
  commands:
    - mdconvert -h
    - mdinspect -h

about:
  home: https://github.com/mdtraj/mdtraj
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A modern, open library for the analysis of molecular dynamics trajectories
  description: |
    MDTraj is a python library that allows users to manipulate molecular dynamics
    (MD) trajectories and perform a variety of analyses, including fast RMSD,
    solvent accessible surface area, hydrogen bonding, etc. A highlight of MDTraj
    is the wide variety of molecular dynamics trajectory file formats which are
    supported, including RCSB pdb, GROMACS xtc, tng, and trr, CHARMM / NAMD dcd, AMBER
    binpos, AMBER NetCDF, AMBER mdcrd, TINKER arc and MDTraj HDF5.
  doc_url: http://mdtraj.org/
  dev_url: https://github.com/mdtraj/mdtraj

extra:
  recipe-maintainers:
    - marscher
    - mattwthompson
    - sroet
    - jeremyleung521
