schema_version: 1

context:
  name: mdtraj
  version: 1.11.0
  python_min: "3.11"

package:
  name: mdtraj
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mdtraj/${{ name }}-${{ version }}.tar.gz
  sha256: 2cf0ed2ee9a603dc4599743b1806e1387c655e2a1e9d013841b99fb137ad852e
build:
  number: 0
  script: ${{ PYTHON }} -m pip install . --no-deps -vv
  python:
    entry_points:
      - mdconvert = mdtraj.scripts.mdconvert:entry_point
      - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python       ${{ python_min }}.*
        - cross-python_${{ target_platform }}
        - cython =3
        - numpy
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - versioneer
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - versioneer
    - cython =3
    - numpy
    - zlib
  run:
    - python >=${{ python_min }}
    - setuptools
    - packaging
    - numpy >=1.25.0,<3
    - scipy
    - pandas
    - pyparsing
    - pytables
    - snappy
    - zlib
  run_constraints:
    - gsd !=3.0.0

tests:
  - python:
      imports:
        - mdtraj
  - script:
      - mdconvert -h
      - mdinspect -h

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A modern, open library for the analysis of molecular dynamics trajectories
  description: |
    MDTraj is a python library that allows users to manipulate molecular dynamics
    (MD) trajectories and perform a variety of analyses, including fast RMSD,
    solvent accessible surface area, hydrogen bonding, etc. A highlight of MDTraj
    is the wide variety of molecular dynamics trajectory file formats which are
    supported, including RCSB pdb, GROMACS xtc, tng, and trr, CHARMM / NAMD dcd, AMBER
    binpos, AMBER NetCDF, AMBER mdcrd, TINKER arc and MDTraj HDF5.
  homepage: https://github.com/mdtraj/mdtraj
  repository: https://github.com/mdtraj/mdtraj
  documentation: http://mdtraj.org/

extra:
  recipe-maintainers:
    - marscher
    - mattwthompson
    - sroet
    - jeremyleung521
