# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

[project]
name = "mdtraj-feedstock"
version = "3.47.0"
description = "Pixi configuration for conda-forge/mdtraj-feedstock"
authors = ["@conda-forge/mdtraj"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
inspect-all = "inspect_artifacts --all-packages"
build = "rattler-build build --recipe recipe"
"build-linux_64_numpy2.0python3.10.____cpython" = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml"
"inspect-linux_64_numpy2.0python3.10.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.10.____cpython.yaml"
"build-linux_64_numpy2.0python3.11.____cpython" = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml"
"inspect-linux_64_numpy2.0python3.11.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.11.____cpython.yaml"
"build-linux_64_numpy2.0python3.12.____cpython" = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml"
"inspect-linux_64_numpy2.0python3.12.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.12.____cpython.yaml"
"build-linux_64_numpy2.0python3.9.____cpython" = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml"
"inspect-linux_64_numpy2.0python3.9.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2.0python3.9.____cpython.yaml"
"build-linux_64_numpy2python3.13.____cp313" = "rattler-build build --recipe recipe -m .ci_support/linux_64_numpy2python3.13.____cp313.yaml"
"inspect-linux_64_numpy2python3.13.____cp313" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_numpy2python3.13.____cp313.yaml"
"build-osx_64_numpy2.0python3.10.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_64_numpy2.0python3.10.____cpython.yaml"
"inspect-osx_64_numpy2.0python3.10.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_numpy2.0python3.10.____cpython.yaml"
"build-osx_64_numpy2.0python3.11.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_64_numpy2.0python3.11.____cpython.yaml"
"inspect-osx_64_numpy2.0python3.11.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_numpy2.0python3.11.____cpython.yaml"
"build-osx_64_numpy2.0python3.12.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_64_numpy2.0python3.12.____cpython.yaml"
"inspect-osx_64_numpy2.0python3.12.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_numpy2.0python3.12.____cpython.yaml"
"build-osx_64_numpy2.0python3.9.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_64_numpy2.0python3.9.____cpython.yaml"
"inspect-osx_64_numpy2.0python3.9.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_numpy2.0python3.9.____cpython.yaml"
"build-osx_64_numpy2python3.13.____cp313" = "rattler-build build --recipe recipe -m .ci_support/osx_64_numpy2python3.13.____cp313.yaml"
"inspect-osx_64_numpy2python3.13.____cp313" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_numpy2python3.13.____cp313.yaml"
"build-osx_arm64_numpy2.0python3.10.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml"
"inspect-osx_arm64_numpy2.0python3.10.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.10.____cpython.yaml"
"build-osx_arm64_numpy2.0python3.11.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml"
"inspect-osx_arm64_numpy2.0python3.11.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.11.____cpython.yaml"
"build-osx_arm64_numpy2.0python3.12.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml"
"inspect-osx_arm64_numpy2.0python3.12.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.12.____cpython.yaml"
"build-osx_arm64_numpy2.0python3.9.____cpython" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml"
"inspect-osx_arm64_numpy2.0python3.9.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2.0python3.9.____cpython.yaml"
"build-osx_arm64_numpy2python3.13.____cp313" = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml"
"inspect-osx_arm64_numpy2python3.13.____cp313" = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_numpy2python3.13.____cp313.yaml"
"build-win_64_numpy2.0python3.10.____cpython" = "rattler-build build --recipe recipe -m .ci_support/win_64_numpy2.0python3.10.____cpython.yaml"
"inspect-win_64_numpy2.0python3.10.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_numpy2.0python3.10.____cpython.yaml"
"build-win_64_numpy2.0python3.11.____cpython" = "rattler-build build --recipe recipe -m .ci_support/win_64_numpy2.0python3.11.____cpython.yaml"
"inspect-win_64_numpy2.0python3.11.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_numpy2.0python3.11.____cpython.yaml"
"build-win_64_numpy2.0python3.12.____cpython" = "rattler-build build --recipe recipe -m .ci_support/win_64_numpy2.0python3.12.____cpython.yaml"
"inspect-win_64_numpy2.0python3.12.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_numpy2.0python3.12.____cpython.yaml"
"build-win_64_numpy2.0python3.9.____cpython" = "rattler-build build --recipe recipe -m .ci_support/win_64_numpy2.0python3.9.____cpython.yaml"
"inspect-win_64_numpy2.0python3.9.____cpython" = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_numpy2.0python3.9.____cpython.yaml"
"build-win_64_numpy2python3.13.____cp313" = "rattler-build build --recipe recipe -m .ci_support/win_64_numpy2python3.13.____cp313.yaml"
"inspect-win_64_numpy2python3.13.____cp313" = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_numpy2python3.13.____cp313.yaml"

[feature.smithy.dependencies]
conda-smithy = "*"

[feature.smithy.tasks]
build-locally = "python ./build-locally.py"
smithy = "conda-smithy"
rerender = "conda-smithy rerender"
lint = "conda-smithy lint recipe"

[environments]
smithy = ["smithy"]
